services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-astaller1
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
      
  postgresql:
    image: postgres:latest 
    container_name: postgresql-astaller1
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
  
  mariadb:
    image: mariadb:latest
    container_name: mariadb-astaller1
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: streamflow_facturacion
      MARIADB_USER: admin
      MARIADB_PASSWORD: root
    ports:
      - "3306:3306"
